wfp/designsystem

bower.json
components/_navigation.scss

- Corrects package version number;
- Corrects package description;

Improves and makes `inline-menu` universal

---

.travis.yml
readme.md

Add TravisCI config to project and build status to docs

---

.travis.yml

Add build and dist tasks for UI guide to TravisCI

---

.eslintrc.json
gruntfile.js
package.json

Feature/eslint #27

---

.sass-lint.yml
scss/components/_buttons.scss
scss/components/_forms.scss

Fixes #21. Checkboxes now display corectly.

Checkbox display update

---

.travis.yml

As per: https://github.com/travis-ci/travis-ci/issues/5092

[CI] Add a workaround for problematic `curl` issue

---

docs/bootstrap.html
scss/bootstrap-theme.scss

Updates `bootstrap-theme` as per #56.

Bootstrap Update

---

docs/_includes/header.html
docs/_includes/sidebar.html
docs/component-2-navigation.md
scss/components/navigation/_menu.scss

Improve display of `menu--heading`

---

.travis.yml
gruntfile.js
package.json

- Add accessibility, HTML5, and link testing (fix #60);
- Add special version of the task for Travis (with `showSummaryOnly` flag);

Accessibility, HTML5, and link validation

---

.travis.yml
gruntfile.js
package.json

- Updates build tools;
- Updates build tasks;
- Updated Travis CI environment;

Update build process

---

docs/example.html
scss/css/_base.scss
scss/modules/elements/_headings.scss

Responsive Headings

---

gruntfile.js
scss/_init.scss
scss/css/_elements.scss
scss/css/_layout.scss
scss/css/_typography.scss

Responsive micro components

---

src/components/FileUploader/index.js

Add ability to use the Filename component
**Changed**
* Filename component export

Add Filename component export

---

package-lock.json
src/components/Search/Search.js

**New**
**Changed**
**Removed**

docs(Search): default kind

---

.storybook/blocks/DocsContainer.tsx
.storybook/storybook.scss
src/components/BannerNavigation/_banner-navigation.scss
src/components/Blockquote/Blockquote.js
src/components/Link/_link.scss
src/components/MainNavigation/_main-navigation.scss
src/components/ReactDropzone/README.mdx
src/components/Value/_value.scss
src/globals/scss/_theme-tokens.scss
src/globals/scss/styles.scss

**New**
**Changed**
**Removed**

docs(React-Dropzone): readme added

---

.storybook/blocks/PurePreview.tsx
.storybook/webpack.config.js
package-lock.json
package.json
src/components/Button/Button.stories.js
src/components/Button/Button.twig
src/documentation/Colours/Colour.stories.mdx
src/documentation/Usage/UsageCss.stories.mdx
src/documentation/Usage/UsageDevelopers.stories.mdx

**New**
**Changed**
**Removed**

docs(Developers): installation guidelines updated

---

.storybook/blocks/PurePreview.tsx

**New**
**Changed**
**Removed**

docs(Twig): inital commit of twig preview

---

.storybook/storybook.scss
src/components/CardNew/_cardnew.scss
src/components/DatePicker/_date-picker.scss
src/components/Modal/_modal.scss
src/components/Notification.legacy/_progressBar.scss
src/components/Tooltip/Tooltip.js
src/globals/scss/_colors.scss
src/globals/scss/_theme-tokens.scss
src/globals/scss/_vars.scss
src/globals/scss/styles.scss
src/index.js

**New**
**Changed**
**Removed**

fix(Colors): variable calculation updated wip

---

package-lock.json
package.json
release.config.js
src/components/Story/Story.stories.js

**New**
**Changed**
**Removed**

docs(Story): minor spacing removed

---

src/components/Button/Button.stories.js

**Removed**
* {{Removed duplicate row in the table for tertiary button type}}

docs(Button): removed duplicate explanation on tertiary button type

---

src/components/Table/Table.stories.js

**Changed**
* Fixed broken  link to React Table in the Table page

docs(Table): fixed broken link to React Table

---

src/index.js

**New**
**Changed**
**Removed**

fix(colors): added colors to export again

---

src/components/Notification/Notification.js

**New**
**Changed**
**Removed**

fix(Notification): icons were wrong

---

src/components/Search/Search.js

**New**
**Changed**
**Removed**

fix(Search): onChange was returning a wrong target value (#368)

---

package-lock.json

**New**
**Changed**
**Removed**

fix(package): lock file updated

---

package.json

**New**
**Changed**
**Removed**

fix(package): manual version bump

---

src/documentation/Logos/Logos.js

**New**
**Changed**
**Removed**

docs(Logos): border removed

---

src/components/Tooltip/Tooltip.js
src/components/Tooltip/Tooltip.stories.js

**New**
**Changed**
**Removed**

docs(Tooltip): added tooltip on icon example

---

.storybook/preview.js
.storybook/storybook.scss
src/components/Button/_button.scss
src/components/Button/_mixins.scss
src/components/NumberInput/_number-input.scss
src/globals/scss/_rtl.scss

**New**
**Changed**
**Removed**

feat(Button): added right to left support

---

src/components/BannerNavigation/_banner-navigation.scss

**New**
**Changed**
**Removed**

fix(BannerNavigation): font-weight changed

---

package-lock.json

**New**
**Changed**
**Removed**

fix(package): added lockfile

---

CHANGELOG.md
package-lock.json
src/documentation/Usage/UsageDevelopers.stories.mdx

**New**
**Changed**
**Removed**

fix(next): branch was not aligned to master

---

package-lock.json
package.json
src/components/Text/_text.scss
src/globals/scss/_css--arabic-font-face.scss
src/globals/scss/_tajawal.scss

**New**
**Changed**
**Removed**

fix(sass): upgrade pipelines for building sass

---

package.json

**New**
**Changed**
**Removed**

fix(package): url to repository has changed

---

src/components/BannerNavigation/BannerNavigationWithContent.js

**New**
**Changed**
**Removed**

feat(BannerNavigation): new content added

---

.storybook/blocks/DocsContainer.tsx
.storybook/blocks/DocsPage.tsx
azure-pipelines.yml

**New**
**Changed**
**Removed**

docs(content):layout fixes for ZH

---

packages/ui/src/index.js
readme.md
yarn.lock

**New**
**Changed**
**Removed**

fix(readme): updated readme for developers

---

packages/styles/scss/components/button/_button.scss
packages/ui/src/components/Button/Button.js
packages/ui/src/components/Button/Button.stories.js
packages/ui/src/components/Button/_button.scss

Creates the new "All caps" version of the Button component from the SMP redesign.
**New**
* New "All caps" Button variant
**Changed**
* Button.stories.js
* Button.js
* Button.scss
**Removed**
No files have been removed

Create the 'all caps' version of the Button component

---

src/components/MainNavigation/MainNavigation.stories.js
src/components/Modal/Modal.js
src/documentation/Logos/Logos.js
src/documentation/Logos/Logos.stories.mdx

Next fixes

---

src/components/FormGroup/FormGroup.stories.js
src/components/Slider/Slider-test.js

**New**
**Changed**
**Removed**

fix(components): making sure azure release new version

---

src/components/Pagination/Pagination.js

Fix next/previous buttons type

---

src/components/Modal/Modal.js
src/components/ModalWrapper/ModalWrapper.js
src/components/ModalWrapper/ModalWrapper.stories.js
src/types/Button.d.ts
src/types/Modal/Modal.d.ts

{{bug fixes on typescript and Proptypes}}
**Changed**
* {{added more propTypes definitions to Modal component}}
* {{passed all other modal props to ModalWrapper component}}
* {{corrected typescript definitions on Modal and Button component}}

fix(components): typescript declaration bug fixes and proper Proptypes

---

src/components/SecondaryNavigation/SecondaryNavigation.js
src/types/Checkbox.d.ts
src/types/Input.d.ts
src/types/Modal/Modal.d.ts
src/types/Navigation/SecondaryNavigation.d.ts
src/types/Navigation/SecondaryNavigationTitle.d.ts
src/types/Navigation/index.d.ts
src/types/RadioButton.d.ts
src/types/Select/Select.d.ts
src/types/TextArea.d.ts
src/types/TextInput.d.ts
src/types/Toggle.d.ts
src/types/Wrapper.d.ts

**New**
* {{added type definitions for SecondaryNavigationTitle}}
**Changed**
* {{SecondaryNavigation, Checkbox.d.ts, Input.d.ts, Modal.d.ts, SecondaryNavigation.d.ts, index.d.ts, RadioButton.d.ts, Select.d.ts, TextArea.d.ts, TextInput.d.ts, Toggle.d.ts, Wrapper.d.ts}}

fix(typescript): bug fixes with proper type definitions

---

src/types/Modal/Modal.d.ts
src/types/Navigation/MainNavigationItem.d.ts

**New**
**Changed**
**Removed**

fix(typescript): type definition fixes

---

src/documentation/Usage/ToolRecommendations.stories.mdx

**New**
**Changed**
**Removed**

docs(tools): updated link to airbnb guidelines

---

package.json

**New**
**Changed**
**Removed**

wfp icon upgrade

---

src/types/Footer.d.ts

**Changed**
Add missing `secondary` prop to `FooterProps` interface

Fix/incorrect Footer props interface
